/**
 * The FretLab content library: drills, routines, chords, scales, and songs.
 *
 * App Template Contract v1 §5: this is domain logic, not presentation. It sits
 * under lib/ so L2 sections and L3 elements can use it without importing from
 * a page, and so the boundary lint has somewhere legal to point.
 */
import type { KeyName } from "./types";
import { intervalShape } from "./theory";

export const DRILLS = [
  {
    id: "position-one",
    name: "Position one, up and back",
    category: "Scale fluency",
    level: "Beginner",
    minutes: 4,
    progress: 72,
    bpm: 84,
    difficulty: 1,
    low: 1,
    high: 5,
    intervals: [0, 2, 4, 5, 7, 9, 11],
    reason: "Build one reliable map before connecting the whole neck.",
    goal: "Two clean round trips",
    cue: "Keep the turnaround in time.",
  },
  {
    id: "root-locator",
    kind: "map",
    name: "Locate every root",
    category: "Neck knowledge",
    level: "Beginner",
    minutes: 3,
    progress: 88,
    bpm: 0,
    difficulty: 1,
    low: 0,
    high: 12,
    intervals: [0],
    reason: "Root notes orient every scale, chord and phrase.",
    goal: "Find all roots in 20 seconds",
    cue: "Say the string name before each note.",
  },
  {
    id: "thirds",
    kind: "box",
    name: "Thirds through the shape",
    category: "Intervals",
    level: "Intermediate",
    minutes: 5,
    progress: 41,
    bpm: 76,
    difficulty: 2,
    low: 1,
    high: 7,
    intervals: [0, 4, 7, 11],
    reason: "Thirds reveal chord quality inside a scale shape.",
    goal: "Three passes without a pause",
    cue: "Hear each pair before you move.",
  },
  {
    id: "major-triad",
    kind: "box",
    name: "Major triad targets",
    category: "Chord tones",
    level: "Beginner",
    minutes: 4,
    progress: 63,
    bpm: 72,
    difficulty: 1,
    low: 0,
    high: 7,
    intervals: [0, 4, 7],
    reason: "The root, third and fifth connect scales directly to chords.",
    goal: "Resolve every phrase to 1",
    cue: "Square roots are your landing points.",
  },
  {
    id: "pentatonic-one",
    name: "Pentatonic box one",
    category: "Scale fluency",
    level: "Beginner",
    minutes: 6,
    progress: 23,
    bpm: 92,
    difficulty: 2,
    low: 3,
    high: 8,
    intervals: [0, 2, 4, 7, 9],
    reason: "Five-note shapes make phrasing easier while time stays steady.",
    goal: "Four even eighth-note passes",
    cue: "Use alternate picking throughout.",
  },
  {
    id: "minor-pentatonic",
    name: "Minor pentatonic phrasing",
    category: "Improvisation",
    level: "Beginner",
    minutes: 6,
    progress: 54,
    bpm: 78,
    difficulty: 2,
    low: 3,
    high: 8,
    intervals: [0, 3, 5, 7, 10],
    reason: "A smaller note set lets rhythm and articulation lead.",
    goal: "Create four two-bar phrases",
    cue: "Leave one beat of space.",
  },
  {
    id: "string-six",
    kind: "map",
    strings: [6],
    name: "String six note sprint",
    category: "Neck knowledge",
    level: "Beginner",
    minutes: 3,
    progress: 67,
    bpm: 0,
    difficulty: 1,
    low: 0,
    high: 12,
    intervals: [0, 2, 4, 5, 7, 9, 11],
    reason: "Low-string roots unlock movable chords and scale positions.",
    goal: "Name all natural notes twice",
    cue: "Look away after the first pass.",
  },
  {
    id: "string-five",
    kind: "map",
    strings: [5],
    name: "String five root map",
    category: "Neck knowledge",
    level: "Beginner",
    minutes: 3,
    progress: 48,
    bpm: 0,
    difficulty: 1,
    low: 0,
    high: 12,
    intervals: [0, 5, 7],
    reason: "Most common movable chord roots begin on strings five and six.",
    goal: "Find 1, 4 and 5 instantly",
    cue: "Connect each root to a chord shape.",
  },
  {
    id: "sixths",
    kind: "box",
    strings: [1, 2, 3],
    name: "Sixths on the top strings",
    category: "Intervals",
    level: "Intermediate",
    minutes: 5,
    progress: 35,
    bpm: 68,
    difficulty: 2,
    low: 3,
    high: 10,
    intervals: [0, 4, 9],
    reason: "Sixths turn scale knowledge into melodic double-stops.",
    goal: "One clean ascent and descent",
    cue: "Let both notes ring together.",
  },
  {
    id: "sevenths",
    kind: "box",
    name: "Leading-tone resolution",
    category: "Intervals",
    level: "Intermediate",
    minutes: 4,
    progress: 29,
    bpm: 64,
    difficulty: 2,
    low: 0,
    high: 9,
    intervals: [0, 11],
    reason: "The seventh-to-root pull makes harmony feel directional.",
    goal: "Hear ten clean resolutions",
    cue: "Let 7 lean into 1.",
  },
  {
    id: "one-four-five",
    kind: "box",
    name: "I–IV–V chord-tone map",
    category: "Chord tones",
    level: "Intermediate",
    minutes: 6,
    progress: 58,
    bpm: 80,
    difficulty: 2,
    low: 0,
    high: 9,
    intervals: [0, 4, 5, 7, 11],
    reason: "These three chords power thousands of progressions.",
    goal: "Track the nearest chord tone",
    cue: "Move the least distance possible.",
  },
  {
    id: "relative-minor",
    kind: "box",
    name: "Relative minor bridge",
    category: "Harmony",
    level: "Intermediate",
    minutes: 5,
    progress: 44,
    bpm: 72,
    difficulty: 2,
    low: 0,
    high: 9,
    intervals: [0, 2, 4, 7, 9],
    reason: "Major and relative minor share notes but change the tonal center.",
    goal: "Resolve four phrases both ways",
    cue: "Change the landing note, not the shape.",
  },
  {
    id: "arpeggio",
    kind: "map",
    name: "Triad arpeggio sequence",
    category: "Chord tones",
    level: "Intermediate",
    minutes: 6,
    progress: 31,
    bpm: 76,
    difficulty: 2,
    low: 0,
    high: 12,
    intervals: [0, 4, 7],
    reason: "Arpeggios make harmony audible one note at a time.",
    goal: "Connect two positions",
    cue: "Accent the root of each octave.",
  },
  {
    id: "two-position",
    kind: "map",
    name: "Two-position connection",
    category: "Scale fluency",
    level: "Intermediate",
    minutes: 7,
    progress: 26,
    bpm: 88,
    difficulty: 2,
    low: 2,
    high: 10,
    intervals: [0, 2, 4, 5, 7, 9, 11],
    reason: "Horizontal shifts replace isolated boxes with one neck-wide map.",
    goal: "Shift without breaking eighth notes",
    cue: "Change position on string three.",
  },
  {
    id: "three-note",
    kind: "box",
    name: "Three-note-per-string run",
    category: "Technique",
    level: "Advanced",
    minutes: 7,
    progress: 18,
    bpm: 96,
    difficulty: 3,
    low: 2,
    high: 10,
    intervals: [0, 2, 4, 5, 7, 9, 11],
    reason: "Consistent string groupings improve synchronization and speed.",
    goal: "Four clean sixteenth-note bars",
    cue: "Lead each new string with the opposite pick.",
  },
  {
    id: "diatonic-sevenths",
    kind: "map",
    name: "Diatonic seventh arpeggios",
    category: "Harmony",
    level: "Advanced",
    minutes: 8,
    progress: 14,
    bpm: 68,
    difficulty: 3,
    low: 0,
    high: 12,
    intervals: [0, 2, 4, 5, 7, 9, 11],
    reason: "Seventh chords expose every scale degree’s harmonic role.",
    goal: "Name all seven chord qualities",
    cue: "Keep common tones ringing.",
  },
  {
    id: "mode-shift",
    kind: "box",
    name: "Major to Mixolydian",
    category: "Harmony",
    level: "Advanced",
    minutes: 6,
    progress: 21,
    bpm: 80,
    difficulty: 3,
    low: 3,
    high: 10,
    intervals: [0, 2, 4, 5, 7, 9, 10],
    reason: "Changing one degree shows how modes reshape a familiar key.",
    goal: "Hear and target the b7",
    cue: "Compare 7 and b7 directly.",
  },
  {
    id: "rhythmic-cells",
    name: "Rhythmic displacement",
    category: "Technique",
    level: "Advanced",
    minutes: 6,
    progress: 16,
    bpm: 84,
    difficulty: 3,
    low: 3,
    high: 8,
    intervals: [0, 2, 4, 7, 9],
    reason:
      "Moving a five-note idea across four beats builds rhythmic control.",
    goal: "Stay aligned for eight bars",
    cue: "Count aloud through the shift.",
  },
] as const;
export type Drill = (typeof DRILLS)[number];
export function drillNotes(drill: Drill, key: KeyName, full = false) {
  return intervalShape(
    key,
    [...drill.intervals],
    full ? 0 : drill.low,
    full ? 12 : drill.high,
  );
}
export const TRAINING_MODULES = [
  {
    id: "locator",
    name: "Note locator",
    level: "Beginner",
    minutes: 3,
    intervals: [0],
    target: "root note",
    instruction: "Find every root across frets one to seven.",
  },
  {
    id: "degrees",
    name: "Scale degrees",
    level: "Beginner",
    minutes: 4,
    intervals: [0, 4, 7],
    target: "1 · 3 · 5",
    instruction: "Find the stable major-triad degrees inside the key.",
  },
  {
    id: "chord-tones",
    name: "Chord tones",
    level: "Intermediate",
    minutes: 5,
    intervals: [0, 3, 7, 10],
    target: "1 · b3 · 5 · b7",
    instruction: "Map a minor-seven sound without relying on a shape.",
  },
  {
    id: "intervals",
    name: "Interval recall",
    level: "Advanced",
    minutes: 5,
    intervals: [0, 2, 5, 9],
    target: "1 · 2 · 4 · 6",
    instruction: "Locate the color tones, then name each distance aloud.",
  },
] as const;
export const ROUTINES = [
  {
    name: "Ten minute warm-up",
    cadence: "Every morning",
    last: "Yesterday",
    completed: 3,
    drills: [
      {
        name: "Open string check",
        key: "G" as KeyName,
        mins: 4,
        phase: "warm",
      },
      { name: "Locate every D", key: "D" as KeyName, mins: 3, phase: "core" },
      {
        name: "Open chord changes",
        key: "C" as KeyName,
        mins: 3,
        phase: "cool",
      },
    ],
  },
  {
    name: "One key, deep",
    cadence: "Three times a week",
    last: "2 days ago",
    completed: 2,
    drills: [
      {
        name: "Position one, up and back",
        key: "G" as KeyName,
        mins: 4,
        phase: "warm",
      },
      {
        name: "Thirds through the shape",
        key: "G" as KeyName,
        mins: 5,
        phase: "core",
      },
      { name: "Chord tones only", key: "G" as KeyName, mins: 4, phase: "core" },
      { name: "Locate every G", key: "G" as KeyName, mins: 3, phase: "cool" },
      {
        name: "Free play over a drone",
        key: "G" as KeyName,
        mins: 2,
        phase: "cool",
      },
    ],
  },
  {
    name: "Neck knowledge",
    cadence: "Weekends",
    last: "Last Sunday",
    completed: 1,
    drills: [
      {
        name: "Pentatonic box one",
        key: "A" as KeyName,
        mins: 4,
        phase: "warm",
      },
      {
        name: "Sixths on the top two",
        key: "E" as KeyName,
        mins: 3,
        phase: "core",
      },
      {
        name: "Open chord changes",
        key: "C" as KeyName,
        mins: 4,
        phase: "core",
      },
      {
        name: "Free play over a drone",
        key: "F" as KeyName,
        mins: 3,
        phase: "cool",
      },
    ],
  },
];

export const CHORDS = [
  {
    id: "g-major",
    root: "G" as KeyName,
    symbol: "G",
    name: "G major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "G · B · D",
    fingering: [
      { s: 6, f: 3, finger: 2 },
      { s: 5, f: 2, finger: 1 },
      { s: 4, f: 0, finger: 0 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 3, finger: 3 },
    ],
    muted: [],
    tip: "Let the open strings ring; keep the third finger relaxed.",
  },
  {
    id: "c-major",
    root: "C" as KeyName,
    symbol: "C",
    name: "C major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "C · E · G",
    fingering: [
      { s: 5, f: 3, finger: 3 },
      { s: 4, f: 2, finger: 2 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 1, finger: 1 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "Curve the first finger so the open high E stays clear.",
  },
  {
    id: "d-major",
    root: "D" as KeyName,
    symbol: "D",
    name: "D major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "D · F# · A",
    fingering: [
      { s: 4, f: 0, finger: 0 },
      { s: 3, f: 2, finger: 1 },
      { s: 2, f: 3, finger: 3 },
      { s: 1, f: 2, finger: 2 },
    ],
    muted: [6, 5],
    tip: "Start from the open D string and avoid the low E.",
  },
  {
    id: "a-major",
    root: "A" as KeyName,
    symbol: "A",
    name: "A major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "A · C# · E",
    fingering: [
      { s: 5, f: 0, finger: 0 },
      { s: 4, f: 2, finger: 1 },
      { s: 3, f: 2, finger: 2 },
      { s: 2, f: 2, finger: 3 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "Keep the three second-fret notes compact and let both A notes ring.",
  },
  {
    id: "e-major",
    root: "E" as KeyName,
    symbol: "E",
    name: "E major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "E · G# · B",
    fingering: [
      { s: 6, f: 0, finger: 0 },
      { s: 5, f: 2, finger: 2 },
      { s: 4, f: 2, finger: 3 },
      { s: 3, f: 1, finger: 1 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [],
    tip: "Place the G# first; it is the note that makes the chord major.",
  },
  {
    id: "f-major",
    root: "F" as KeyName,
    symbol: "F",
    name: "F major",
    quality: "Major",
    formula: "1 · 3 · 5",
    notes: "F · A · C",
    fingering: [
      { s: 6, f: 1, finger: 1 },
      { s: 5, f: 3, finger: 3 },
      { s: 4, f: 3, finger: 4 },
      { s: 3, f: 2, finger: 2 },
      { s: 2, f: 1, finger: 1 },
      { s: 1, f: 1, finger: 1 },
    ],
    muted: [],
    tip: "Use arm weight instead of squeezing the full first-fret barre.",
  },
  {
    id: "e-minor",
    root: "E" as KeyName,
    symbol: "Em",
    name: "E minor",
    quality: "Minor",
    formula: "1 · b3 · 5",
    notes: "E · G · B",
    fingering: [
      { s: 6, f: 0, finger: 0 },
      { s: 5, f: 2, finger: 2 },
      { s: 4, f: 2, finger: 3 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [],
    tip: "Use two adjacent fingers and listen for all six strings.",
  },
  {
    id: "a-minor",
    root: "A" as KeyName,
    symbol: "Am",
    name: "A minor",
    quality: "Minor",
    formula: "1 · b3 · 5",
    notes: "A · C · E",
    fingering: [
      { s: 5, f: 0, finger: 0 },
      { s: 4, f: 2, finger: 2 },
      { s: 3, f: 2, finger: 3 },
      { s: 2, f: 1, finger: 1 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "Think of C major with fingers two and three shifted inward.",
  },
  {
    id: "b-minor",
    root: "B" as KeyName,
    symbol: "Bm",
    name: "B minor",
    quality: "Minor",
    formula: "1 · b3 · 5",
    notes: "B · D · F#",
    fingering: [
      { s: 5, f: 2, finger: 1 },
      { s: 4, f: 4, finger: 3 },
      { s: 3, f: 4, finger: 4 },
      { s: 2, f: 3, finger: 2 },
      { s: 1, f: 2, finger: 1 },
    ],
    muted: [6],
    tip: "Build the barre first, then place the compact minor shape.",
  },
  {
    id: "d-seven",
    root: "D" as KeyName,
    symbol: "D7",
    name: "D dominant seven",
    quality: "Seventh",
    formula: "1 · 3 · 5 · b7",
    notes: "D · F# · A · C",
    fingering: [
      { s: 4, f: 0, finger: 0 },
      { s: 3, f: 2, finger: 2 },
      { s: 2, f: 1, finger: 1 },
      { s: 1, f: 2, finger: 3 },
    ],
    muted: [6, 5],
    tip: "The C on string two creates the pull back toward G.",
  },
  {
    id: "c-major-seven",
    root: "C" as KeyName,
    symbol: "Cmaj7",
    name: "C major seven",
    quality: "Seventh",
    formula: "1 · 3 · 5 · 7",
    notes: "C · E · G · B",
    fingering: [
      { s: 5, f: 3, finger: 3 },
      { s: 4, f: 2, finger: 2 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "Lift the first finger from C major to reveal the open B.",
  },
  {
    id: "g-seven",
    root: "G" as KeyName,
    symbol: "G7",
    name: "G dominant seven",
    quality: "Seventh",
    formula: "1 · 3 · 5 · b7",
    notes: "G · B · D · F",
    fingering: [
      { s: 6, f: 3, finger: 3 },
      { s: 5, f: 2, finger: 2 },
      { s: 4, f: 0, finger: 0 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 1, finger: 1 },
    ],
    muted: [],
    tip: "Keep the first-fret F clear; it creates the pull toward C.",
  },
  {
    id: "a-seven",
    root: "A" as KeyName,
    symbol: "A7",
    name: "A dominant seven",
    quality: "Seventh",
    formula: "1 · 3 · 5 · b7",
    notes: "A · C# · E · G",
    fingering: [
      { s: 5, f: 0, finger: 0 },
      { s: 4, f: 2, finger: 1 },
      { s: 3, f: 0, finger: 0 },
      { s: 2, f: 2, finger: 3 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "Let the open G ring between the two second-fret notes.",
  },
  {
    id: "e-seven",
    root: "E" as KeyName,
    symbol: "E7",
    name: "E dominant seven",
    quality: "Seventh",
    formula: "1 · 3 · 5 · b7",
    notes: "E · G# · B · D",
    fingering: [
      { s: 6, f: 0, finger: 0 },
      { s: 5, f: 2, finger: 2 },
      { s: 4, f: 0, finger: 0 },
      { s: 3, f: 1, finger: 1 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [],
    tip: "Compare it with E major: lifting one finger reveals the b7.",
  },
  {
    id: "a-sus-two",
    root: "A" as KeyName,
    symbol: "Asus2",
    name: "A suspended two",
    quality: "Sus2",
    formula: "1 · 2 · 5",
    notes: "A · B · E",
    fingering: [
      { s: 5, f: 0, finger: 0 },
      { s: 4, f: 2, finger: 1 },
      { s: 3, f: 2, finger: 2 },
      { s: 2, f: 0, finger: 0 },
      { s: 1, f: 0, finger: 0 },
    ],
    muted: [6],
    tip: "The open B removes the third, leaving an open, unresolved color.",
  },
  {
    id: "b-diminished",
    root: "B" as KeyName,
    symbol: "Bdim",
    name: "B diminished",
    quality: "Diminished",
    formula: "1 · b3 · b5",
    notes: "B · D · F",
    fingering: [
      { s: 5, f: 2, finger: 1 },
      { s: 4, f: 3, finger: 2 },
      { s: 3, f: 4, finger: 4 },
      { s: 2, f: 3, finger: 3 },
    ],
    muted: [6, 1],
    tip: "Use the compact symmetry to hear how strongly it wants to resolve to C.",
  },
].map((chord, index) => ({
  ...chord,
  level:
    index < 8 || chord.quality.startsWith("Sus")
      ? "Beginner"
      : index < 15
        ? "Intermediate"
        : "Advanced",
}));
export const SCALES = [
  {
    id: "major",
    name: "Major",
    family: "Major",
    level: "Beginner",
    mood: "clear · resolved",
    formula: "W W H W W W H",
    intervals: [0, 2, 4, 5, 7, 9, 11],
  },
  {
    id: "natural-minor",
    name: "Natural minor",
    family: "Minor",
    level: "Beginner",
    mood: "dark · grounded",
    formula: "W H W W H W W",
    intervals: [0, 2, 3, 5, 7, 8, 10],
  },
  {
    id: "major-pentatonic",
    name: "Major pentatonic",
    family: "Pentatonic",
    level: "Beginner",
    mood: "open · melodic",
    formula: "1 2 3 5 6",
    intervals: [0, 2, 4, 7, 9],
  },
  {
    id: "minor-pentatonic",
    name: "Minor pentatonic",
    family: "Pentatonic",
    level: "Beginner",
    mood: "direct · bluesy",
    formula: "1 b3 4 5 b7",
    intervals: [0, 3, 5, 7, 10],
  },
  {
    id: "blues",
    name: "Blues",
    family: "Minor",
    level: "Intermediate",
    mood: "gritty · expressive",
    formula: "1 b3 4 b5 5 b7",
    intervals: [0, 3, 5, 6, 7, 10],
  },
  {
    id: "dorian",
    name: "Dorian",
    family: "Modes",
    level: "Intermediate",
    mood: "minor · lifted",
    formula: "1 2 b3 4 5 6 b7",
    intervals: [0, 2, 3, 5, 7, 9, 10],
  },
  {
    id: "mixolydian",
    name: "Mixolydian",
    family: "Modes",
    level: "Intermediate",
    mood: "major · restless",
    formula: "1 2 3 4 5 6 b7",
    intervals: [0, 2, 4, 5, 7, 9, 10],
  },
  {
    id: "harmonic-minor",
    name: "Harmonic minor",
    family: "Minor",
    level: "Intermediate",
    mood: "dramatic · magnetic",
    formula: "1 2 b3 4 5 b6 7",
    intervals: [0, 2, 3, 5, 7, 8, 11],
  },
  {
    id: "lydian",
    name: "Lydian",
    family: "Modes",
    level: "Advanced",
    mood: "bright · floating",
    formula: "1 2 3 #4 5 6 7",
    intervals: [0, 2, 4, 6, 7, 9, 11],
  },
  {
    id: "phrygian",
    name: "Phrygian",
    family: "Modes",
    level: "Advanced",
    mood: "dark · tense",
    formula: "1 b2 b3 4 5 b6 b7",
    intervals: [0, 1, 3, 5, 7, 8, 10],
  },
  {
    id: "melodic-minor",
    name: "Melodic minor",
    family: "Minor",
    level: "Advanced",
    mood: "modern · fluid",
    formula: "1 2 b3 4 5 6 7",
    intervals: [0, 2, 3, 5, 7, 9, 11],
  },
];
export const SONGS = [
  {
    id: "stand-by-me",
    title: "Stand by Me",
    artist: "Ben E. King",
    key: "A" as KeyName,
    level: "Beginner",
    capo: "2nd fret",
    tempo: 118,
    progression: ["G", "Em", "C", "D"],
    focus: "Four-chord pocket",
    image: "/guitar-stage.jpg",
  },
  {
    id: "dreams",
    title: "Dreams",
    artist: "Fleetwood Mac",
    key: "F" as KeyName,
    level: "Beginner",
    capo: "None",
    tempo: 120,
    progression: ["F", "G"],
    focus: "Time and consistency",
    image: "/guitar-strings.jpg",
  },
  {
    id: "house-rising-sun",
    title: "House of the Rising Sun",
    artist: "Traditional",
    key: "A" as KeyName,
    level: "Intermediate",
    capo: "None",
    tempo: 78,
    progression: ["Am", "C", "D", "F", "E"],
    focus: "Arpeggio control",
    image: "/guitar-neck.jpg",
  },
  {
    id: "three-little-birds",
    title: "Three Little Birds",
    artist: "Bob Marley",
    key: "A" as KeyName,
    level: "Beginner",
    capo: "None",
    tempo: 76,
    progression: ["A", "D", "E"],
    focus: "Off-beat rhythm",
    image: "/guitar-stage.jpg",
  },
  {
    id: "knockin",
    title: "Knockin’ on Heaven’s Door",
    artist: "Bob Dylan",
    key: "G" as KeyName,
    level: "Beginner",
    capo: "None",
    tempo: 70,
    progression: ["G", "D", "Am", "C"],
    focus: "Smooth changes",
    image: "/guitar-strings.jpg",
  },
  {
    id: "sweet-home",
    title: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    key: "D" as KeyName,
    level: "Intermediate",
    capo: "None",
    tempo: 98,
    progression: ["D", "C", "G"],
    focus: "Riff articulation",
    image: "/guitar-neck.jpg",
  },
];

